version: '2'
services:
    rabbit:
        image: "rabbitmq:3"
        ports:
            - "5672:5672"
    vokaturi:
        build:
            context: .
            dockerfile: ./VokaturiAudio/Dockerfile
        image: "wkronmiller/vokaturi-audio"
        links:
            - rabbit
